#!/bin/sh

matchbox-window-manager -use_titlebar no -use_desktop_mode plain&

numlockx off
#necessary with some DVI-HDMI adaptors
#xscreensaver&

setxkbmap -option ctrl:nocaps
xmodmap -e 'keycode 77 = NoSymbol'



#uncomment for keyboard with real numpad
#setxkbmap -option numpad:mac


# uncomment while loop if we can run nodm for non dualseat
while true
do
  firefox -new-instance --kiosk https://roprotokol.danskestudentersroklub.dk
done
