#!/bin/sh

matchbox-window-manager -use_titlebar no -use_desktop_mode plain&

numlockx on
#necessary with some DVI-HDMI adaptors
#xscreensaver&

setxkbmap -option ctrl:nocaps

#uncomment for keyboard with real numpad
#setxkbmap -option numpad:mac


# uncomment while loop if we can run nodm for non dualseat
while true
do
  firefox --kiosk -P dsr https://roprotokol.danskestudentersroklub.dk
done
