#!/bin/sh

matchbox-window-manager -use_titlebar no -use_desktop_mode plain&

numlockx on
#necessary with some DVI-HDMI adaptors
xscreensaver&

setxkbmap -option ctrl:nocaps
setxkbmap -option numpad:mac

while true
do
  firefox --kiosk -P dsr https://roprotokol.danskestudentersroklub.dk
done
