ALTER TABLE Member ADD COLUMN Gender BOOLEAN DEFAULT NULL COMMENT '0=Male, 1=Female';

ALTER TABLE tblMembersToRoprotokol ADD COLUMN Sex VARCHAR(2) DEFAULT NULL, ADD COLUMN Birthdate DATETIME DEFAULT NULL;

