UPDATE Skade SET FK_Reperatør=2000+ROUND(RAND()*999);
UPDATE Skade SET FK_Ansvarlig=2000+ROUND(RAND()*999);
DELETE FROM Skade WHERE Beskrivelse LIKE "%Jens%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%Hans%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%Morten%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%Dan%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%Søren%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%Thomas%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%Kasper%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%gaard%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%Henrik%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%Jørn%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%Rune%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%Niels%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%Reiner%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%Jørgen%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%Rasmus%";
DELETE FROM Skade WHERE Beskrivelse LIKE "%Nico%";
