DELETE FROM TripRights;
INSERT INTO TripRights (trip_type,required_right,requirement) VALUES (1,"rowright","all");
INSERT INTO TripRights (trip_type,required_right,requirement) VALUES (1,"cox","cox"); 
INSERT INTO TripRights (trip_type,required_right,requirement) VALUES (3,"langtursstyrmand","cox");
INSERT INTO TripRights (trip_type,required_right,requirement) VALUES (3,"rowright","all"); 
INSERT INTO TripRights (trip_type,required_right,requirement) VALUES (5,"instruktør","any");
INSERT INTO TripRights (trip_type,required_right,requirement) VALUES (7,"rowright","all");
INSERT INTO TripRights (trip_type,required_right,requirement) VALUES (7,"cox","cox"); 
INSERT INTO TripRights (trip_type,required_right,requirement) VALUES (14,"rowright","all");
INSERT INTO TripRights (trip_type,required_right,requirement) VALUES (14,"cox","cox"); 
INSERT INTO TripRights (trip_type,required_right,requirement) VALUES (9,"cox","cox");
INSERT INTO TripRights (trip_type,required_right,requirement) VALUES (9,"rowright","all"); 
INSERT INTO TripRights (trip_type,required_right,requirement) VALUES (10,"outriggerinstruktør","cox");
