#!/bin/sh
#
git rev-parse HEAD | awk  'END { print "<?php\n$gitrevision=\"" $1 "\";\n"}' > public/inc/gitrevision.php
git rev-parse HEAD | awk  'END { print "var gitrevision=\"" $1 "\";\n"}' > public/js/gitrevision.js
